pixel_processing <- function(pixel) {
  source('accumulating.R')
  source('differenting.R')
  source('segmenting.R')
  source('erosing.R')
  source('masking.R')
  #barplot(pixel, xlab="Velocity Range 40 [km s^-1]", axes=FALSE)
  #title(main="Velocity Spectra for a PP Pixel",sub="Perseus 13CO emission in L1448")
  #box()
  #Sys.sleep(0.5)
  #dev.off()
  print("... spectral processing (accumulating)...")
  h <- accumulating(pixel)
  #barplot(h, xlab="Velocity Range 40 [km s^-1]", axes=FALSE)
  #title(main="Accumulated Vel Spectra for a PP Pixel",sub="Perseus 13CO emission in L1448")
  #box()
  #Sys.sleep(0.5)
  #dev.off()
  print("... spectral processing (differenting)...")
  diff <- differenting(h)
  #barplot(diff, xlab="Velocity Range 40 [km s^-1]", axes=FALSE)
  #title(main="Differenced Vel Spectra for a PP Pixel",sub="Perseus 13CO emission in L1448")
  #box()
  #Sys.sleep(0.5)
  #dev.off()
  print("... spectral processing (segmenting)...")
  boxing <- segmenting(diff)
  #barplot(boxing, xlab="Velocity Range 40 [km s^-1]", axes=FALSE)
  #title(main="Segmented Vel Spectra for a PP Pixel",sub="Perseus 13CO emission in L1448")
  #box()
  #Sys.sleep(0.3)
  #dev.off()
  print("... spectral processing (erosing)...")
  boxing <- erosing(boxing)
  pixel_masked <- masking(boxing,pixel)
  #barplot(pixel_masked, xlab="Velocity Range 40 [km s^-1]", axes=FALSE)
  #title(main="Filtered Vel Spectra for a PP Pixel",sub="Perseus 13CO emission in L1448")
  #box()
  #Sys.sleep(0.5)
  #dev.off()
  print("... spectral processing (masking)...")
  return(pixel_masked)
}
