library("FITSio")
library("biOps")
library("EBImage")
library("DBI")
library("RPostgreSQL")
source("~/Desktop/Alumnos/Gabriel_Candia/codes/getAbsCoord.R")
source("~/Desktop/Alumnos/Gabriel_Candia/codes/calculateCoords.R")
source("~/Desktop/Alumnos/Gabriel_Candia/codes/writeToDataBase.R")
source("~/Desktop/Alumnos/Gabriel_Candia/codes/getCoordData.R")
source("~/Desktop/Alumnos/Gabriel_Candia/codes/getObjects.R")
source("~/Desktop/Alumnos/Gabriel_Candia/codes/mainFunction.R")
drv <- dbDriver("PostgreSQL")
database <- dbConnect(drv, dbname="alma", user="postgres", password="cygnus")
fits <- "http://das.sdss.org/www/cgi-bin/drC?RUN=3630&RERUN=40&CAMCOL=3&FIELD=83&FILTER=r"
mainFunction(database,fits)